#ifndef MESSAGEBUBBLE_GLOBAL_H
#define MESSAGEBUBBLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGEBUBBLE_LIBRARY)
#define MESSAGEBUBBLE_EXPORT Q_DECL_EXPORT
#else
#define MESSAGEBUBBLE_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGEBUBBLE_GLOBAL_H
